import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const ownerA='00000000-0000-4000-8000-000000000001',ownerB='00000000-0000-4000-8000-000000000002',member='00000000-0000-4000-8000-000000000003';
const product='10000000-0000-4000-8000-000000000001',sale='20000000-0000-4000-8000-000000000001';
test('PostgreSQL: tenant isolation, stock accounting, checkout, evidence and retries',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text default 'test@example.invalid',email_confirmed_at timestamptz default now());
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,storage to authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,created_at timestamptz default now());
 alter table storage.objects enable row level security;grant select,insert on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;
 insert into auth.users(id,email) values('${ownerA}','owner-a@example.com'),('${ownerB}','admin@example.com'),('${member}','member@example.com');`);
 await db.exec(await readFile('supabase/migrations/202609090001_make_it.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/202609090002_validation_and_cleanup.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/202609090003_admin.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/202609120001_sale_time_and_customer.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/202609120002_membership_and_permissions.sql','utf8'));
 const asUser=async(id:string)=>{await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}'`)};
 const call=async(sql:string,params:unknown[]=[])=>db.query<Record<string,any>>(sql,params);
 await asUser(ownerA);const sa=(await call("select makeit_setup_shop('ร้านเอ') id")).rows[0].id;
 const ownerSnapshot=(await call('select makeit_snapshot() d')).rows[0].d;assert.equal(ownerSnapshot.access.role,'owner');assert.equal(ownerSnapshot.access.can_export,true);
 await asUser(member);await call('select makeit_join_shop($1)',[ownerSnapshot.access.join_code]);const memberSnapshot=(await call('select makeit_snapshot() d')).rows[0].d;
 assert.equal(memberSnapshot.shop.id,sa);assert.equal(memberSnapshot.access.role,'member');assert.equal(memberSnapshot.access.can_export,false);assert.equal(memberSnapshot.members.length,0);
 await assert.rejects(()=>call("select makeit_setup_shop('ห้ามสร้างซ้ำ')"),/เป็นสมาชิก/);
 await asUser(ownerA);assert.equal((await call('select makeit_snapshot() d')).rows[0].d.members.length,2);await call('select makeit_remove_member($1)',[member]);
 await call('select makeit_save_product($1,$2,$3,100,60,10,true,null)',[product,'กาแฟ','เครื่องดื่ม']);
 await assert.rejects(()=>call("select makeit_save_product($1,'bad','', 'NaN'::numeric,0,0,true,null)",['10000000-0000-4000-8000-000000000099']),/makeit_finite_prices/);
 await call("select makeit_stock('30000000-0000-4000-8000-000000000001',$1,'purchase',10,80,true,'รับเข้า')",[product]);
 let p=(await call('select * from makeit_products')).rows[0];assert.equal(Number(p.average_cost),70);assert.equal(p.stock,20);
 await call("select makeit_stock('30000000-0000-4000-8000-000000000001',$1,'purchase',10,80,true,'รับเข้า')",[product]);
 assert.equal((await call('select * from makeit_products')).rows[0].stock,20,'repeated purchase is idempotent');
 assert.equal(Number((await call('select * from makeit_cash_entries')).rows[0].amount),800);
 await assert.rejects(()=>call('select makeit_checkout($1,$2,\'transfer\',null)',[sale,JSON.stringify([{id:product,quantity:1}])]),/กรุณาแนบสลิป/);
 await assert.rejects(()=>call('select makeit_checkout($1,$2,\'cash\',null)',[sale,JSON.stringify([{id:product,quantity:1.5}])]),/จำนวนสินค้า/);
 await assert.rejects(()=>call('select makeit_checkout($1,$2,\'cash\',null)',[sale,JSON.stringify([{id:product,quantity:21}])]),/ไม่เพียงพอ/);
 assert.equal((await call('select * from makeit_sales')).rows.length,0,'failed checkout rolls back entirely');
 await call('select makeit_checkout($1,$2,\'cash\',null)',[sale,JSON.stringify([{id:product,quantity:2},{id:product,quantity:1}])]);
 await call('select makeit_checkout($1,$2,\'cash\',null)',[sale,JSON.stringify([{id:product,quantity:3}])]);
 assert.equal((await call('select * from makeit_sales')).rows.length,1);assert.equal((await call('select * from makeit_products')).rows[0].stock,17);
 assert.equal(Number((await call('select * from makeit_sales')).rows[0].cost),210);
 await call('select makeit_save_product($1,$2,$3,120,999,999,true,null)',[product,'กาแฟใหม่','เครื่องดื่ม']);
 assert.equal(Number((await call('select * from makeit_sale_items')).rows[0].price),100,'historical price stays immutable');
 assert.equal((await call('select * from makeit_products')).rows[0].stock,17,'metadata edit cannot set stock');
 const timedProduct='10000000-0000-4000-8000-000000000002',timedSale='20000000-0000-4000-8000-000000000099';
 await call('select makeit_save_product($1,$2,$3,40,20,2,true,null)',[timedProduct,'ชาไทย','เครื่องดื่ม']);
 await assert.rejects(()=>call("select makeit_checkout_v2($1,$2,'cash',null,now()+interval '1 day','Student','manual',null)",[timedSale,JSON.stringify([{id:timedProduct,quantity:1}])]),/เวลาขายไม่ถูกต้อง/);
 await call("select makeit_checkout_v2($1,$2,'cash',null,'2026-09-10 09:15:00+07','Other','manual',null)",[timedSale,JSON.stringify([{id:timedProduct,quantity:1}])]);
 const timed=(await call('select * from makeit_sales where id=$1',[timedSale])).rows[0];
 assert.equal(timed.customer_type,'Other');assert.equal(timed.time_source,'manual');assert.equal(new Date(timed.created_at).toISOString(),'2026-09-10T02:15:00.000Z');assert.ok(timed.recorded_at);
 await assert.rejects(()=>call('update makeit_products set stock=999'),/permission denied/);
 await assert.rejects(()=>call('select makeit_cleanup_candidates()'),/permission denied/);
 await asUser(ownerB);await call("select makeit_setup_shop('ร้านบี')");
 for(const table of ['makeit_products','makeit_sales','makeit_sale_items','makeit_cash_entries','makeit_movements'])assert.equal((await call(`select * from ${table}`)).rows.length,0,`${table} isolated`);
 await assert.rejects(()=>call('select makeit_checkout($1,$2,\'cash\',null)',['20000000-0000-4000-8000-000000000002',JSON.stringify([{id:product,quantity:1}])]),/ไม่พบสินค้า/);
 await assert.rejects(()=>call('select makeit_void($1,\'bad\')',[sale]),/ไม่พบบิล/);
 await assert.rejects(()=>call('insert into storage.objects(bucket_id,name) values(\'makeit-private\',$1)',[`${sa}/attack.jpg`]),/row-level security/);
 await asUser(ownerA);
 await call("select makeit_void($1,'คืนเงินและสินค้า')",[sale]);await call("select makeit_void($1,'ซ้ำ')",[sale]);
 assert.equal((await call('select * from makeit_products')).rows[0].stock,20,'void restores stock only once');
 await call("select makeit_stock('30000000-0000-4000-8000-000000000002',$1,'purchase',1,90,false,'ยังไม่จ่าย')",[product]);
 const unpaid=(await call("select * from makeit_movements where request_id='30000000-0000-4000-8000-000000000002'")).rows[0];
 await call('select makeit_pay_purchase($1)',[unpaid.id]);await call('select makeit_pay_purchase($1)',[unpaid.id]);
 assert.equal((await call('select * from makeit_cash_entries')).rows.length,2,'delayed purchase payment counted once');
 await assert.rejects(()=>call("select makeit_stock('30000000-0000-4000-8000-000000000003',$1,'adjustment',0,0,false,'')",[product]),/เหตุผล/);
 await call("select makeit_stock('30000000-0000-4000-8000-000000000003',$1,'adjustment',1,0,false,'ตรวจนับ')",[product]);
 const requests=await Promise.allSettled([
  call('select makeit_checkout($1,$2,\'cash\',null)',['20000000-0000-4000-8000-000000000003',JSON.stringify([{id:product,quantity:1}])]),
  call('select makeit_checkout($1,$2,\'cash\',null)',['20000000-0000-4000-8000-000000000004',JSON.stringify([{id:product,quantity:1}])])]);
 assert.equal(requests.filter(r=>r.status==='fulfilled').length,1,'only one sale can consume last item');
 assert.equal((await call('select * from makeit_products')).rows[0].stock,0);
 // Old, unattached uploads are marked for deletion; a live reference is protected.
 await db.exec('reset role');await call("insert into storage.objects(bucket_id,name,created_at) values('makeit-private',$1,now()-interval '2 days'),('makeit-private',$2,now()-interval '2 days')",[`${sa}/unused.jpg`,`${sa}/used.jpg`]);
 await asUser(ownerA);await call('select makeit_save_product($1,$2,$3,120,0,0,true,$4)',[product,'กาแฟ','เครื่องดื่ม',`${sa}/used.jpg`]);
 await db.exec('reset role');const candidates=(await call('select makeit_cleanup_candidates() path')).rows.map(r=>r.path);assert.deepEqual(candidates,[`${sa}/unused.jpg`]);
 await asUser(ownerA);await assert.rejects(()=>call('select makeit_save_product($1,$2,$3,120,0,0,true,$4)',[product,'กาแฟ','เครื่องดื่ม',`${sa}/unused.jpg`]),/อัปโหลดอีกครั้ง/);
 await asUser(ownerB);assert.equal((await call('select * from storage.objects')).rows.length,0,'private files isolated');
 await db.exec('reset role; set role anon');await assert.rejects(()=>call('select makeit_snapshot()'),/permission denied/);
 await asUser(ownerB);
 await assert.rejects(()=>call('select makeit_admin_overview()'),/ไม่มีสิทธิ์/);
 await assert.rejects(()=>call('insert into makeit_admins(user_id) values($1)',[ownerB]),/permission denied/);
 await assert.rejects(()=>call('select makeit_admin_restore_sale($1,\'hack\')',[sale]),/permission denied/);
 await db.exec('reset role');await call('insert into makeit_admins(user_id) values($1)',[ownerB]);await asUser(ownerB);
 assert.equal((await call('select makeit_admin_overview() d')).rows[0].d.total_shops,2);
 const snap=async()=>(await call('select makeit_admin_shop($1) d',[sa])).rows[0].d;
 let ad=await snap();
 await call("select makeit_admin_add_member($1,'member@example.com')",[sa]);ad=await snap();assert.equal(ad.members.length,2);
 await call('select makeit_admin_remove_member($1,$2)',[sa,member]);ad=await snap();assert.equal(ad.members.length,1);
 const mutate=async(action:string,target:string,expected:unknown,data:unknown,id=crypto.randomUUID(),reason='แก้ไขข้อมูลทดสอบ')=>call('select makeit_admin_mutate($1,$2,$3,$4,$5,$6,$7) d',[id,sa,action,target,JSON.stringify(expected),JSON.stringify(data),reason]);
 const originalProduct=ad.products.find((p:any)=>p.id===product);const editProduct={...originalProduct,stock:10,average_cost:50};const req=crypto.randomUUID();
 await mutate('product',product,originalProduct,editProduct,req);
 await mutate('product',product,originalProduct,editProduct,req);
 assert.equal((await snap()).audit.length,3,'admin retries only create one additional audit');
 await assert.rejects(()=>mutate('product',product,originalProduct,editProduct),/เปลี่ยนแล้ว/);
 ad=await snap();assert.equal(ad.products.find((p:any)=>p.id===product).stock,10);
 await assert.rejects(()=>mutate('product',product,ad.products.find((p:any)=>p.id===product),editProduct,crypto.randomUUID(),''),/เหตุผล/);
 await assert.rejects(()=>call('delete from makeit_admin_audit'),/permission denied/);
 const live=ad.sales.find((s:any)=>!s.voided_at);
 const originalItem=ad.items.find((i:any)=>i.sale_id===live.id);
 const changed={payment:'cash',created_at:live.created_at,items:[{id:product,quantity:originalItem.quantity,price:150}]};
 const fixId=crypto.randomUUID();await mutate('sale',live.id,live,changed,fixId);
 ad=await snap();assert.equal(ad.products.find((p:any)=>p.id===product).stock,10,'price-only correction preserves stock');
 assert.equal(Number(ad.items.find((i:any)=>i.sale_id===fixId).cost),Number(originalItem.cost),'historical cost survives price correction');
 assert.ok(ad.sales.find((s:any)=>s.id===live.id).voided_at,'original bill retained and voided');
 await mutate('sale',live.id,live,changed,fixId);assert.equal((await snap()).audit.length,4);
 const replacement=ad.sales.find((s:any)=>s.id===fixId);
 await assert.rejects(()=>mutate('sale',fixId,replacement,{...changed,items:[{id:product,quantity:999,price:150}]}),/ไม่เพียงพอ/);
 assert.equal((await snap()).sales.find((s:any)=>s.id===fixId).voided_at,null,'failed correction rolls back void');
 await mutate('void_sale',fixId,replacement,{});assert.equal((await snap()).products.find((p:any)=>p.id===product).stock,11);
 assert.equal((await call('select * from storage.objects')).rows.length,2,'admin can inspect private shop evidence');
 await call("insert into storage.objects(bucket_id,name) values('makeit-private',$1)",[`${sa}/admin.jpg`]);
 await assert.rejects(()=>call("insert into storage.objects(bucket_id,name) values('makeit-private','invalid/admin.jpg')"),/row-level security/);
 await asUser(ownerA);await assert.rejects(()=>call('select makeit_admin_shop($1)',[sa]),/ไม่มีสิทธิ์/);
 await db.close();
});
