'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import Decimal from 'decimal.js';
import {Store,Package,ReceiptText,Wallet,ChartNoAxesCombined,Plus,Search,ShoppingBag,Minus,ArrowRight,ChevronRight,RefreshCw,LogOut,Settings,Download,FileText,ArrowUpRight,ArrowDownRight,Check,Camera,CheckCircle2,Trash2,Banknote,Landmark,Clock,Box,TriangleAlert} from 'lucide-react';
import Auth from '@/components/auth';
import {AdminLink} from '@/components/admin-link';
import {Modal,Logo,Photo,Evidence,Empty,Submit,FileField,errorText} from '@/components/ui';
import {ProductForm,StockForm,CashForm} from '@/components/forms';
import {supabase,rpc,upload} from '@/lib/supabase';
import {emptySnapshot,type Snapshot,type Cart,type Product,type Sale} from '@/lib/types';
import {baht,money,report,thaiDay,thaiTime,thaiDate,summaryRows} from '@/lib/reports';
type Page='pos'|'products'|'sales'|'cash'|'reports';
type Dialog={kind:'product';product?:Product}|{kind:'stock';product:Product}|{kind:'sale';sale:Sale}|{kind:'cash'}|{kind:'settings'}|{kind:'checkout'}|null;
type Attempt={id:string;items:{id:string;quantity:number}[];payment:'cash'|'transfer';slip:string|null};
const nav=[{id:'pos' as Page,label:'หน้าร้าน',icon:Store},{id:'products' as Page,label:'สินค้า',icon:Package},{id:'sales' as Page,label:'ประวัติขาย',icon:ReceiptText},{id:'cash' as Page,label:'รายรับรายจ่าย',icon:Wallet},{id:'reports' as Page,label:'รายงาน',icon:ChartNoAxesCombined}];
export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[recovery,setRecovery]=useState(false),[data,setData]=useState<Snapshot>(emptySnapshot);
 const[page,setPage]=useState<Page>('pos'),[modal,setModal]=useState<Dialog>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 const[cart,setCart]=useState<Cart>({}),[cartLoaded,setCartLoaded]=useState(''),[attempt,setAttempt]=useState<Attempt|null>(null),[cartOpen,setCartOpen]=useState(false);
 const[search,setSearch]=useState(''),[category,setCategory]=useState('ทั้งหมด'),[from,setFrom]=useState(thaiDay()),[to,setTo]=useState(thaiDay());
 const[payment,setPayment]=useState<'cash'|'transfer'>('cash'),[slip,setSlip]=useState<File|null>(null),[checkoutError,setCheckoutError]=useState('');
 const actionLock=useRef(false);
 const currentUid=useRef<string|null>(null);
 const refresh=useCallback(async()=>{const uid=currentUid.current;if(!uid)return;setLoading(true);try{const result=await rpc<Snapshot>('makeit_snapshot');if(currentUid.current!==uid)return;if(result.shop&&result.shop.owner_id!==uid)return;setData(result);setError('')}catch(e){if(currentUid.current===uid)setError(errorText(e))}finally{if(currentUid.current===uid)setLoading(false)}},[]);
 useEffect(()=>{try{const sb=supabase();const{data:{subscription}}=sb.auth.onAuthStateChange((event,s)=>{currentUid.current=s?.user.id??null;setSession(s);setReady(true);if(event==='PASSWORD_RECOVERY')setRecovery(true);if(!s){setData(emptySnapshot);setCart({});setAttempt(null);setCartLoaded('');setModal(null)}});sb.auth.getSession().then(({data:{session:s}})=>{currentUid.current=s?.user.id??null;setSession(s);setReady(true);if(location.search.includes('recovery=1'))setRecovery(true)});return()=>subscription.unsubscribe()}catch(e){setError(errorText(e));setReady(true)}},[]);
 useEffect(()=>{if(session)void refresh()},[session?.user.id,refresh]);
 useEffect(()=>{if(!session)return;const focus=()=>void refresh();window.addEventListener('focus',focus);window.addEventListener('online',focus);return()=>{window.removeEventListener('focus',focus);window.removeEventListener('online',focus)}},[session,refresh]);
 useEffect(()=>{if(!data.shop)return;const key=`makeit-cart:${data.shop.id}`;if(cartLoaded!==key){try{const saved=JSON.parse(localStorage.getItem(key)??'{}');setCart(saved.cart??{});setAttempt(saved.attempt??null);if(saved.attempt){setPayment(saved.attempt.payment);setModal({kind:'checkout'})}}catch{setCart({});setAttempt(null)}setCartLoaded(key)}},[data.shop,cartLoaded]);
 useEffect(()=>{if(cartLoaded)try{localStorage.setItem(cartLoaded,JSON.stringify({cart,attempt}))}catch{setError('พื้นที่จัดเก็บในเครื่องเต็ม กรุณาเปิดพื้นที่ว่างก่อนขาย')}},[cart,attempt,cartLoaded]);
 useEffect(()=>{if(attempt&&data.sales.some(s=>s.id===attempt.id)){setCart({});setAttempt(null);setModal(null);setCartOpen(false);setNotice('บันทึกการขายสำเร็จแล้ว');}},[data.sales,attempt]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)}},[notice]);
 const r=report(data,from,to),today=report(data,thaiDay(),thaiDay());
 const cartItems=Object.entries(cart).map(([id,quantity])=>({product:data.products.find(p=>p.id===id),quantity})).filter((x):x is {product:Product;quantity:number}=>!!x.product);
 const total=cartItems.reduce((a,x)=>a.plus(new Decimal(x.product.price).times(x.quantity)),new Decimal(0));
 const count=cartItems.reduce((a,x)=>a+x.quantity,0);
 function add(p:Product,delta:number){if(attempt)return;setCart(c=>{const n=Math.max(0,Math.min(p.stock,(c[p.id]??0)+delta));const next={...c};if(n)next[p.id]=n;else delete next[p.id];return next})}
 async function done(){setModal(null);setNotice('บันทึกเรียบร้อย');await refresh()}
 async function setup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await rpc('makeit_setup_shop',{p_name:new FormData(e.currentTarget).get('name')});await refresh();setModal(null)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function checkout(){if(actionLock.current)return;actionLock.current=true;setBusy(true);setCheckoutError('');try{
  let req=attempt;
  if(!req){if(!count)throw new Error('กรุณาเลือกสินค้า');if(payment==='transfer'&&!slip)throw new Error('กรุณาถ่ายรูปหรือเลือกสลิปก่อนบันทึก');const path=payment==='transfer'&&slip?await upload(data.shop!.id,slip):null;req={id:crypto.randomUUID(),items:cartItems.map(x=>({id:x.product.id,quantity:x.quantity})),payment,slip:path};
   localStorage.setItem(cartLoaded,JSON.stringify({cart,attempt:req}));setAttempt(req);
  }
  const{error:err}=await supabase().rpc('makeit_checkout',{p_request:req.id,p_items:req.items,p_payment:req.payment,p_slip:req.slip});
  if(err){if(err.code==='P0001'||err.code?.startsWith('22')||err.code?.startsWith('23')){setAttempt(null);localStorage.setItem(cartLoaded,JSON.stringify({cart,attempt:null}));}throw new Error(err.message)}
  localStorage.removeItem(cartLoaded);setAttempt(null);setCart({});setSlip(null);setModal(null);setCartOpen(false);setNotice('ขายสำเร็จ บันทึกบิลและตัดสต็อกแล้ว');await refresh();
 }catch(e){setCheckoutError(errorText(e))}finally{setBusy(false);actionLock.current=false}}
 async function exportFile(kind:'xlsx'|'pdf'){if(from>to){setError('วันเริ่มต้องไม่เกินวันสิ้นสุด');return}setBusy(true);try{const x=await import('@/lib/exports');await(kind==='xlsx'?x.exportExcel:x.exportPDF)(data,from,to)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 if(!ready)return <div className="splash"><Logo large/><p>กำลังเปิดร้าน…</p></div>;
 if(!session||recovery)return <><Auth recovery={recovery&&!!session} onRecovered={()=>{setRecovery(false);history.replaceState({},'',location.pathname)}}/>{error&&<div className="config-alert" role="alert">{error}</div>}</>;
 if(!data.shop)return <main className="setup-page"><div className="setup-card"><Logo/><h1>{loading?'กำลังเปิดร้าน…':'ตั้งชื่อร้านของคุณ'}</h1><p className="muted">อีกนิดเดียว ก็พร้อมเริ่มบันทึกการขายแล้ว</p>{!loading&&<form onSubmit={setup}><label>ชื่อร้าน<input name="name" placeholder="เช่น ร้านกาแฟของฉัน" maxLength={100} required/></label><Submit busy={busy}>เริ่มใช้งาน<ArrowRight size={18}/></Submit></form>}{error&&<div className="alert error">{error}<button className="text-button" onClick={refresh}>ลองอีกครั้ง</button></div>}<AdminLink/><button className="text-button" onClick={()=>supabase().auth.signOut()}>ออกจากระบบ</button></div></main>;
 const products=data.products.filter(p=>(page==='products'||p.active)&&p.name.toLowerCase().includes(search.toLowerCase())&&(category==='ทั้งหมด'||p.category===category));
 const categories=['ทั้งหมด',...Array.from(new Set(data.products.filter(p=>p.active).map(p=>p.category).filter(Boolean)))];
 const title={pos:'พร้อมสำหรับการขายวันนี้',products:'สินค้าของร้าน',sales:'ประวัติการขาย',cash:'รายรับรายจ่าย',reports:'ภาพรวมของร้าน'}[page];
 const subtitle={pos:'เลือกสินค้า แล้วเริ่มบันทึกการขายได้เลย',products:'ดูแลสินค้า ราคา และสต็อกในที่เดียว',sales:'ทุกรายการขาย พร้อมหลักฐานที่ย้อนดูได้',cash:'บันทึกเงินเข้าออก ให้รู้ทุกความเคลื่อนไหว',reports:'เข้าใจยอดขาย ต้นทุน และกำไรของคุณ'}[page];
 const cartPanel=<><div className="cart-heading"><div><h2>รายการขาย</h2><span className="muted">{count} ชิ้นในตะกร้า</span></div><ShoppingBag size={22}/></div><div className="cart-lines">{!cartItems.length?<div className="cart-empty"><ShoppingBag size={44}/><h3>เริ่มต้นบิลใหม่</h3><p>แตะสินค้าเพื่อเพิ่มในรายการขาย</p></div>:cartItems.map(({product:p,quantity:q})=><div className="cart-line" key={p.id}><Photo path={p.image_path} name={p.name}/><div className="cart-line-body"><strong>{p.name}</strong><small>{baht(p.price)} / ชิ้น</small><div className="quantity"><button disabled={!!attempt} aria-label={`ลด ${p.name}`} onClick={()=>add(p,-1)}><Minus size={14}/></button><span>{q}</span><button disabled={!!attempt||q>=p.stock} aria-label={`เพิ่ม ${p.name}`} onClick={()=>add(p,1)}><Plus size={14}/></button></div></div><b>{baht(new Decimal(p.price).times(q))}</b></div>)}</div><div className="cart-bottom"><div className="total"><span>ยอดรวม</span><strong>{baht(total)}</strong></div><p className="cart-hint"><ShieldIcon/>บันทึกยอดขายและสต็อกพร้อมกัน</p><button className="btn primary full" disabled={!count&&!attempt} onClick={()=>{setCheckoutError('');setModal({kind:'checkout'})}}>{attempt?'ตรวจสอบบิลที่รอบันทึก':'ชำระเงิน'}<ArrowRight size={18}/></button></div></>;
 return <div className="app-shell"><aside className="sidebar"><Logo/><div className="shop-label"><span className="shop-avatar"><Store size={20}/></span><div><strong>{data.shop.name}</strong><small>ร้านของคุณ</small></div></div><span className="nav-label">พื้นที่ทำงาน</span><nav>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setSearch('');setCategory('ทั้งหมด')}}><n.icon size={21}/>{n.label}{page===n.id&&<span className="active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><AdminLink/><div className="online-label"><span/>เชื่อมต่อข้อมูลร้าน</div><button onClick={()=>setModal({kind:'settings'})}><Settings size={18}/>ตั้งค่าร้าน</button><button onClick={async()=>{if(attempt){setError('กรุณาบันทึกบิลที่ค้างอยู่ให้เสร็จก่อนออกจากระบบ');return}await supabase().auth.signOut();}}><LogOut size={18}/>ออกจากระบบ</button><small>MAKE IT · MOBILE POS</small></div></aside><div className="workspace"><header className="topbar"><div className="mobile-brand"><Logo/></div><div className="breadcrumb">ร้านของคุณ <ChevronRight size={14}/><strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><span className="date-text">{new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'long'}).format(new Date())}</span><button className="icon-btn" aria-label="รีเฟรชข้อมูล" onClick={refresh}><RefreshCw size={18} className={loading?'spin':''}/></button><button className="avatar" aria-label="ตั้งค่าร้าน" onClick={()=>setModal({kind:'settings'})}>{data.shop.name.slice(0,1)}</button></div></header><main className="main-content"><div className="page-heading"><div><span className="eyebrow">{page==='pos'?'LET’S MAKE IT A GOOD DAY':'MAKE IT • YOUR BUSINESS'}</span><h1>{title}<span className="blue-dot">.</span></h1><p>{subtitle}</p></div>{(page==='pos'||page==='products')&&<button className="btn primary" onClick={()=>setModal({kind:'product'})}><Plus size={18}/>เพิ่มสินค้า</button>}{page==='cash'&&<button className="btn primary" onClick={()=>setModal({kind:'cash'})}><Plus size={18}/>เพิ่มรายการ</button>}</div>{error&&<div className="alert error" role="alert"><TriangleAlert size={18}/>{error}<button onClick={()=>setError('')} aria-label="ปิดข้อความ">×</button></div>}{notice&&<div className="toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}
 {(page==='pos'||page==='reports')&&<div className="stats-grid"><Stat label={page==='pos'?'ยอดขายวันนี้':'ยอดขายสุทธิ'} value={baht(page==='pos'?today.revenue:r.revenue)} icon={<Wallet/>} primary detail={page==='pos'?'เริ่มต้นวันใหม่ ไปด้วยกัน':'ไม่รวมบิลที่ยกเลิก'}/><Stat label="รายการขายสำเร็จ" value={`${page==='pos'?today.bills:r.bills}`} unit="บิล" icon={<ReceiptText/>} detail={`${page==='pos'?today.units:r.units} ชิ้นที่ขายได้`}/><Stat label="กำไรขั้นต้น" value={baht(page==='pos'?today.gross:r.gross)} icon={<ChartNoAxesCombined/>} detail="ยอดขาย หักต้นทุนสินค้า"/><Stat label={page==='pos'?'สินค้าพร้อมขาย':'กำไรสุทธิ'} value={page==='pos'?`${data.products.filter(p=>p.active&&p.stock>0).length}`:baht(r.net)} unit={page==='pos'?'รายการ':undefined} icon={<Package/>} detail={page==='pos'?`${data.products.filter(p=>p.active&&p.stock<=5).length} รายการเหลือน้อย (ไม่เกิน 5 ชิ้น)`:'รวมรายรับอื่น หักค่าใช้จ่าย'}/></div>}
 {(page==='pos'||page==='products')&&<div className={page==='pos'?'pos-layout':''}><section className="catalog"><div className="section-heading"><h2>{page==='pos'?'เลือกสินค้า':'รายการสินค้าทั้งหมด'} <span className="count-badge">{products.length}</span></h2><div className="search"><Search size={18}/><input placeholder="ค้นหาชื่อสินค้า…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="ค้นหาสินค้า"/></div></div>{page==='pos'&&<div className="category-tabs">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>}{!products.length?<Empty title={search?'ไม่พบสินค้าที่ค้นหา':'เพิ่มสินค้าชิ้นแรกของร้าน'} detail={search?'ลองค้นหาด้วยชื่ออื่น':'ใส่ชื่อ ราคา และจำนวน แล้วเริ่มขายได้เลย'}>{!search&&<button className="btn primary" onClick={()=>setModal({kind:'product'})}><Plus size={16}/>เพิ่มสินค้า</button>}</Empty>:<div className="product-grid">{products.map(p=><article className={`product-card ${!p.active?'inactive':''}`} key={p.id}><button className="product-visual" onClick={()=>page==='pos'?add(p,1):setModal({kind:'product',product:p})} disabled={page==='pos'&&(p.stock===0||!!attempt)} aria-label={page==='pos'?`เลือก ${p.name}`:`แก้ไข ${p.name}`}><Photo path={p.image_path} name={p.name}/><span className={`stock-badge ${p.stock<=5?'low':''}`}>{!p.active?'ปิดขาย':p.stock===0?'หมด':`เหลือ ${p.stock}`}</span></button><div className="product-info"><small>{p.category||'สินค้าทั่วไป'}</small><h3>{p.name}</h3><div className="product-price"><strong>{baht(p.price)}</strong>{page==='pos'?<button className="add-product" aria-label={`เพิ่ม ${p.name} ลงตะกร้า`} disabled={!p.stock||!!attempt} onClick={()=>add(p,1)}><Plus size={19}/></button>:<button className="text-button" onClick={()=>setModal({kind:'stock',product:p})}>สต็อก <ChevronRight size={15}/></button>}</div>{page==='products'&&<button className="edit-product" onClick={()=>setModal({kind:'product',product:p})}>แก้ไขสินค้า · ต้นทุน {baht(p.average_cost)}</button>}</div></article>)}</div>}</section>{page==='pos'&&<aside className={`cart-panel ${cartOpen?'mobile-open':''}`}>{cartOpen&&<button className="text-button mobile-close" onClick={()=>setCartOpen(false)}>ปิดตะกร้า</button>}{cartPanel}</aside>}</div>}
 {page==='sales'&&<section className="panel"><DateFilter from={from} to={to} setFrom={setFrom} setTo={setTo}/>{!r.sales.length?<Empty title="ยังไม่มีรายการขายในช่วงนี้" detail="เมื่อขายสำเร็จ บิลและหลักฐานจะแสดงที่นี่"/>:<div className="list">{r.sales.map(s=><button className="sale-row" key={s.id} onClick={()=>setModal({kind:'sale',sale:s})}><span className={`row-icon ${s.voided_at?'red':''}`}><ReceiptText size={22}/></span><div className="row-main"><strong>บิล #{String(s.bill_no).padStart(5,'0')}</strong><small>{thaiDate(s.created_at)} · {s.payment==='cash'?'เงินสด':'เงินโอน'}</small></div><div className="row-end"><b>{baht(s.total)}</b><span className={`status ${s.voided_at?'cancelled':''}`}>{s.voided_at?'ยกเลิก':'สำเร็จ'}</span></div><ChevronRight size={18}/></button>)}</div>}</section>}
 {page==='cash'&&<><div className="stats-grid three"><Stat label="เงินเข้ารวม" value={baht(r.cashIn)} icon={<ArrowDownRight/>} detail="ยอดขาย + รายรับอื่น"/><Stat label="เงินออกรวม" value={baht(r.cashOut)} icon={<ArrowUpRight/>} detail="ซื้อสินค้า + ค่าใช้จ่าย"/><Stat label="เงินสุทธิ" value={baht(r.cashNet)} icon={<Wallet/>} detail="เงินเข้า ลบเงินออก" primary/></div><section className="panel"><DateFilter from={from} to={to} setFrom={setFrom} setTo={setTo}/><p className="panel-note">ยอดขายรวมอัตโนมัติจากบิล • ตารางนี้แสดงรายรับอื่นและรายจ่ายที่บันทึก</p>{!r.entries.length?<Empty title="ยังไม่มีรายรับรายจ่าย" detail="เพิ่มค่าใช้จ่ายหรือรายรับอื่นของร้านได้ที่นี่"/>:<div className="list">{r.entries.map(e=><div className="cash-row" key={e.id}><span className={`row-icon ${e.kind!=='income'?'orange':''}`}>{e.kind==='income'?<ArrowDownRight/>:<ArrowUpRight/>}</span><div className="row-main"><strong>{e.category}</strong><small>{thaiDate(e.occurred_at)}{e.note?` · ${e.note}`:''}</small>{e.evidence_path&&<details><summary>ดูหลักฐาน</summary><Evidence path={e.evidence_path}/></details>}</div><b className={e.kind==='income'?'positive':'negative'}>{e.kind==='income'?'+':'−'}{baht(e.amount)}</b></div>)}</div>}</section><Unpaid data={data} onDone={refresh}/></>}
 {page==='reports'&&<><section className="panel"><div className="report-toolbar"><DateFilter from={from} to={to} setFrom={setFrom} setTo={setTo}/><div className="export-buttons"><button className="btn secondary" disabled={busy} onClick={()=>exportFile('xlsx')}><Download size={17}/>Excel</button><button className="btn primary" disabled={busy} onClick={()=>exportFile('pdf')}><FileText size={17}/>PDF</button></div></div><div className="report-grid"><div><h2>รายรับและต้นทุน</h2>{summaryRows(r).slice(3,14).map(([label,value])=><div className="report-line" key={label}><span>{label}</span><b>{baht(value)}</b></div>)}</div><div><div className="forecast"><span className="eyebrow">มองไปข้างหน้า</span><h3>กำไรคาดการณ์จากสต็อก</h3><strong>{baht(r.expected)}</strong><p>หากขายสินค้าคงเหลือทั้งหมดได้ที่ราคาปัจจุบัน<br/>ยังไม่หักค่าใช้จ่ายในอนาคต</p><div>มูลค่าต้นทุนสต็อก <b>{baht(r.stockValue)}</b></div></div><h3 className="payment-heading">สัดส่วนการรับชำระ</h3><div className="payment-bar"><span style={{width:`${r.revenue?r.cash/r.revenue*100:0}%`}}/></div><div className="payment-legend"><span><i/>เงินสด {baht(r.cash)}</span><span><i/>เงินโอน {baht(r.transfer)}</span></div></div></div><p className="panel-note">รายงานตามเวลาประเทศไทย • บิลยกเลิกถูกนำออกจากยอดวันที่ขายเดิม • สต็อกแสดงยอดปัจจุบัน</p></section></>}
 </main><footer className="workspace-footer">MAKE IT <span>ทุกการขาย มีความหมาย</span></footer></div><nav className="mobile-nav">{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setCartOpen(false);setSearch('');setCategory('ทั้งหมด')}}><n.icon size={21}/><span>{n.label}</span></button>)}</nav>{page==='pos'&&!cartOpen&&(count>0||attempt)&&<button className="mobile-cart-bar" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><span>{count} ชิ้น · ดูตะกร้า</span><b>{baht(total)}</b><ArrowRight size={18}/></button>}
 {modal&&<Modal title={modal.kind==='product'?(modal.product?'แก้ไขสินค้า':'เพิ่มสินค้า'):modal.kind==='stock'?'จัดการสต็อก':modal.kind==='cash'?'บันทึกรายรับรายจ่าย':modal.kind==='settings'?'ตั้งค่าร้าน':modal.kind==='sale'?`บิล #${String(modal.sale.bill_no).padStart(5,'0')}`:'ตรวจสอบและชำระเงิน'} onClose={()=>{if(!busy)setModal(null)}}>{modal.kind==='product'&&<ProductForm product={modal.product} shopId={data.shop.id} onDone={done}/>} {modal.kind==='stock'&&<StockForm product={modal.product} shopId={data.shop.id} onDone={done}/>} {modal.kind==='cash'&&<CashForm shopId={data.shop.id} onDone={done}/>} {modal.kind==='settings'&&<form onSubmit={setup}><AdminLink/><label>ชื่อร้าน<input name="name" defaultValue={data.shop.name} required maxLength={100}/></label><label>อีเมล<input value={session.user.email??''} disabled/></label><div className="info-box">เพิ่ม MAKE IT ไปยังหน้าจอโฮมจากเมนูแชร์บน iPhone หรือเมนูติดตั้งแอปบน Android</div><Submit busy={busy}>บันทึกชื่อร้าน</Submit><button className="text-button danger" type="button" onClick={async()=>{if(attempt){setError('กรุณาบันทึกบิลที่ค้างอยู่ก่อน');return}await supabase().auth.signOut()}}>ออกจากระบบ</button></form>} {modal.kind==='sale'&&<SaleDetail sale={modal.sale} data={data} onDone={done}/>} {modal.kind==='checkout'&&<div className="checkout"><div className="checkout-total"><span>ยอดที่ต้องชำระ</span><strong>{baht(total)}</strong><small>{count} ชิ้น · {cartItems.length} รายการ</small></div><div className="checkout-items">{cartItems.map(({product:p,quantity:q})=><div key={p.id}><span>{p.name} × {q}</span><b>{baht(new Decimal(p.price).times(q))}</b></div>)}</div><div className="payment-options"><button disabled={!!attempt||busy} className={payment==='cash'?'selected':''} onClick={()=>setPayment('cash')}><Banknote/>เงินสด{payment==='cash'&&<Check size={16}/>}</button><button disabled={!!attempt||busy} className={payment==='transfer'?'selected':''} onClick={()=>setPayment('transfer')}><Landmark/>เงินโอน{payment==='transfer'&&<Check size={16}/>}</button></div>{payment==='transfer'&&!attempt&&<FileField label="สลิปโอนเงิน" required onChange={setSlip} disabled={busy}/>} {attempt?.slip&&<Evidence path={attempt.slip}/>}<p className="info-box">{attempt?'มีคำขอที่รอยืนยัน กดตรวจสอบ/บันทึกอีกครั้งได้โดยไม่สร้างบิลซ้ำ':'ตรวจยอดรับเงินจริงก่อนยืนยัน ภาพสลิปเป็นหลักฐานประกอบ ไม่ใช่การตรวจสอบกับธนาคาร'}</p>{checkoutError&&<div className="alert error" role="alert">{checkoutError}</div>}<button className="btn primary full" disabled={busy} onClick={checkout}>{busy?<RefreshCw className="spin" size={18}/>:<CheckCircle2 size={18}/>} {busy?'กำลังบันทึก…':attempt?'ตรวจสอบ / บันทึกอีกครั้ง':'ยืนยันการขาย'}</button></div>}</Modal>}
 </div>;
}
function ShieldIcon(){return <CheckCircle2 size={13}/>}
function Stat({label,value,unit,icon,detail,primary=false}:{label:string;value:string;unit?:string;icon:React.ReactNode;detail:string;primary?:boolean}){return <div className={`stat-card ${primary?'stat-primary':''}`}><div className="stat-top"><span>{label}</span><i>{icon}</i></div><div className="stat-value">{value} {unit&&<small>{unit}</small>}</div><p>{detail}</p></div>}
function DateFilter({from,to,setFrom,setTo}:{from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void}){return <div className="date-filter"><label>จากวันที่<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value||thaiDay())}/></label><span>—</span><label>ถึงวันที่<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value||thaiDay())}/></label><button className="text-button" onClick={()=>{setFrom(thaiDay());setTo(thaiDay())}}>วันนี้</button></div>}
function SaleDetail({sale:s,data,onDone}:{sale:Sale;data:Snapshot;onDone:()=>Promise<void>}){
 const[voiding,setVoiding]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function cancel(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{await rpc('makeit_void',{p_sale:s.id,p_reason:new FormData(e.currentTarget).get('reason')});await onDone()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <><div className="bill-meta"><span>{thaiDate(s.created_at)}</span><span className={`status ${s.voided_at?'cancelled':''}`}>{s.voided_at?'ยกเลิกแล้ว':'สำเร็จ'}</span></div><div className="checkout-items">{data.items.filter(i=>i.sale_id===s.id).map(i=><div key={i.id}><span>{i.name} × {i.quantity}<small>{baht(i.price)} / ชิ้น</small></span><b>{baht(new Decimal(i.price).times(i.quantity))}</b></div>)}</div><div className="total"><span>รวม ({s.payment==='cash'?'เงินสด':'เงินโอน'})</span><strong>{baht(s.total)}</strong></div>{s.slip_path&&<Evidence path={s.slip_path}/>} {s.voided_at?<div className="alert error">ยกเลิกเมื่อ {thaiDate(s.voided_at)}<br/>{s.void_reason}<br/>สินค้าคืนเข้าสต็อกแล้ว</div>:voiding?<form onSubmit={cancel}><label>เหตุผลยกเลิก<input name="reason" required maxLength={500} placeholder="เช่น บันทึกรายการผิด / คืนเงินแล้ว"/></label><p className="info-box">จะคืนสินค้าทุกชิ้นเข้าสต็อกและนำยอดออกจากรายงาน กรุณาดำเนินการคืนเงินจริงแยกต่างหาก</p><Submit busy={busy}>ยืนยันยกเลิกบิล</Submit></form>:<button className="btn danger-outline full" onClick={()=>setVoiding(true)}><Trash2 size={17}/>ยกเลิกทั้งบิล</button>}{error&&<div className="alert error">{error}</div>}</>;
}
function Unpaid({data,onDone}:{data:Snapshot;onDone:()=>Promise<void>}){
 const[busy,setBusy]=useState(''),[error,setError]=useState('');const unpaid=data.movements.filter(m=>m.kind==='purchase'&&m.quantity*m.unit_cost>0&&!data.entries.some(e=>e.movement_id===m.id));
 if(!unpaid.length)return null;
 return <section className="panel unpaid"><h2>ค่าซื้อสินค้าที่ยังไม่บันทึกจ่าย</h2>{unpaid.map(m=><div className="cash-row" key={m.id}><div className="row-main"><strong>{data.products.find(p=>p.id===m.product_id)?.name}</strong><small>{thaiDate(m.created_at)} · {m.quantity} ชิ้น</small></div><b>{baht(new Decimal(m.quantity).times(m.unit_cost))}</b><button className="btn secondary" disabled={!!busy} onClick={async()=>{setBusy(m.id);try{await rpc('makeit_pay_purchase',{p_movement:m.id});await onDone()}catch(e){setError(errorText(e))}finally{setBusy('')}}}>{busy===m.id?'กำลังบันทึก…':'จ่ายแล้ว'}</button></div>)}{error&&<div className="alert error">{error}</div>}</section>;
}
