'use client';
import {useEffect,useRef,useState} from 'react';
import Auth from '@/components/auth';
import {Logo,LoadingScreen,Modal,Submit,Evidence,FileField,errorText} from '@/components/ui';
import {rpc,supabase,upload} from '@/lib/supabase';
import type {Snapshot} from '@/lib/types';
import {baht,money,thaiDate,thaiDay,summaryRows,report} from '@/lib/reports';
import {LayoutDashboard,Store,Users,ReceiptText,ShieldCheck,Trash2,RefreshCw,Search} from 'lucide-react';

type Audit={id:string;actor_id:string;action:string;reason:string;created_at:string;before_data:unknown;after_data:unknown};
type ShopData=Snapshot & {owner_email:string;audit:Audit[]};
type Overview={total_shops:number;matched_shops:number;total_members:number;total_sales:number;total_revenue:number;total_corrections:number;shops:{id:string;name:string;email:string;product_count:number;member_count:number;sale_count:number;revenue:number;last_activity:string}[]};
type Edit={action:'shop'|'product'|'entry'|'sale'|'void_sale';row:Record<string,any>};
const movementNames:Record<string,string>={opening:'สต็อกเริ่มต้น',purchase:'รับสินค้าเข้า',adjustment:'ปรับสต็อก',sale:'ขายสินค้า',void:'คืนสต็อกจากยกเลิกบิล'};
const actionNames={shop:'ชื่อร้าน',product:'สินค้าและสต็อก',entry:'รายรับรายจ่าย',sale:'แก้ไขบิล',void_sale:'ยกเลิกบิล',member_add:'เพิ่มสมาชิก',member_remove:'ถอดสมาชิก'};
const localTime=(s:string)=>new Date(new Date(s).getTime()+7*3600000).toISOString().slice(0,16);

export default function Admin(){
 const[uid,setUid]=useState<string|null>(null),[ready,setReady]=useState(false),[allowed,setAllowed]=useState<boolean|null>(null);
 const[overview,setOverview]=useState<Overview|null>(null),[data,setData]=useState<ShopData|null>(null),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[tab,setTab]=useState('activity');
 const[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[contentReady,setContentReady]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[deleteShop,setDeleteShop]=useState(false),[from,setFrom]=useState(thaiDay()),[to,setTo]=useState(thaiDay());
 const identity=useRef<string|null>(null);const generation=useRef(0);
 useEffect(()=>{const sb=supabase();const {data:{subscription}}=sb.auth.onAuthStateChange((_event,s)=>{const next=s?.user.id??null;if(identity.current!==next){identity.current=next;generation.current++;setAllowed(null);setContentReady(false);setData(null);setOverview(null);setEdit(null)}setUid(next);setReady(true)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!uid)return;let alive=true;rpc<boolean>('makeit_is_admin').then(v=>{if(alive)setAllowed(v)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[uid]);
 async function load(shopId?:string){const g=++generation.current;setLoading(true);setError('');try{if(shopId){const d=await rpc<ShopData>('makeit_admin_shop',{p_shop:shopId});if(g===generation.current)setData(d)}else{const d=await rpc<Overview>('makeit_admin_overview',{p_search:search,p_offset:offset});if(g===generation.current)setOverview(d)}}catch(e){if(g===generation.current)setError(errorText(e))}finally{if(g===generation.current){setLoading(false);setContentReady(true)}}}
 useEffect(()=>{if(allowed)void load()},[allowed,offset]);
 if(!ready)return <LoadingScreen label="กำลังเปิดระบบ Admin" admin/>;
 if(!uid)return <Auth onRecovered={()=>{}}/>;
 if(allowed===null)return <LoadingScreen label="กำลังตรวจสอบสิทธิ์ Admin" admin/>;
 if(allowed===false)return <main className="auth-page"><div className="auth-card"><Logo/><h1>ไม่มีสิทธิ์เข้าหน้า Admin</h1>{error&&<p role="alert">{error}</p>}<a className="btn primary" href="/">กลับหน้าร้าน</a><button className="btn secondary" onClick={()=>supabase().auth.signOut()}>ออกจากระบบ</button></div></main>;
 if(!contentReady)return <LoadingScreen label="กำลังเตรียมหน้า Admin" admin/>;
 const editRow=(action:Edit['action'],row:object)=>setEdit({action,row});
 const activities=data?[...data.movements.map(m=>({id:m.id,time:m.created_at,title:`${data.products.find(p=>p.id===m.product_id)?.name??'สินค้า'} · ${movementNames[m.kind]??m.kind}`,detail:`${m.quantity>0?'+':''}${m.quantity} ชิ้น · ${m.reason??''}`})),...data.entries.map(e=>({id:e.id,time:e.occurred_at,title:e.category,detail:`${baht(e.amount)} · ${e.note}`}))].sort((a,b)=>b.time.localeCompare(a.time)):[];
 return <main className="admin-page"><header className="admin-header"><div className="admin-brand"><Logo/><div><strong>Control Center</strong><small>MAKE IT Administration</small></div></div><div className="admin-header-actions"><span className="role-chip"><ShieldCheck size={15}/>SYSTEM ADMIN</span><a className="btn secondary" href="/"><Store size={16}/>หน้าร้าน</a><button className="btn secondary" onClick={()=>supabase().auth.signOut()}>ออกจากระบบ</button></div></header>
 {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert" role="status">{notice}</div>}
 <div className="admin-hero"><div><span className="eyebrow">ADMIN WORKSPACE</span><h1>{data?.shop?.name??'ภาพรวมระบบ'}</h1><p>{data?`เจ้าของร้าน ${data.owner_email}`:'ติดตามร้านค้า สมาชิก ยอดขาย และประวัติการดูแลระบบจากที่เดียว'}</p></div><button className="btn secondary" disabled={loading} onClick={()=>load(data?.shop?.id)}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'กำลังโหลด…':'รีเฟรชข้อมูล'}</button></div>
 {!data&&overview&&<><div className="admin-stats">{[[<Store key="i"/>,'ร้านค้าทั้งหมด',overview.total_shops],[<Users key="i"/>,'สมาชิกทีม',overview.total_members],[<ReceiptText key="i"/>,'บิลสำเร็จ',overview.total_sales],[<LayoutDashboard key="i"/>,'ยอดขายรวม',baht(overview.total_revenue)],[<ShieldCheck key="i"/>,'การแก้ไขโดย Admin',overview.total_corrections]].map(([icon,k,v])=><div className="admin-stat-card" key={String(k)}><span>{icon}</span><div><small>{k}</small><h2>{v}</h2></div></div>)}</div><form className="admin-search" onSubmit={e=>{e.preventDefault();if(offset)setOffset(0);else void load()}}><Search size={19}/><input aria-label="ค้นหาร้าน" placeholder="ค้นหาชื่อร้านหรืออีเมลเจ้าของร้าน" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn primary">ค้นหา</button></form><section className="admin-shop-grid">{overview.shops.map(s=><button className="admin-shop-card" key={s.id} onClick={()=>{setTab('activity');void load(s.id)}}><div className="admin-shop-icon"><Store/></div><div className="admin-shop-main"><strong>{s.name}</strong><small>{s.email}</small><div><span>{s.product_count} สินค้า</span><span>{s.member_count} สมาชิก</span><span>{s.sale_count} บิล</span></div></div><div className="admin-shop-revenue"><small>ยอดขาย</small><b>{baht(s.revenue)}</b><span>ล่าสุด {thaiDate(s.last_activity)}</span></div></button>)}{!overview.shops.length&&<div className="panel">ไม่พบร้านค้าที่ค้นหา</div>}</section><div className="admin-pagination"><button className="btn secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>ก่อนหน้า</button><span>{offset+1}–{offset+overview.shops.length} จาก {overview.matched_shops}</span><button className="btn secondary" disabled={offset+30>=overview.matched_shops} onClick={()=>setOffset(offset+30)}>ถัดไป</button></div></>}
 {data&&data.shop&&<><div className="admin-shop-toolbar"><button className="btn secondary" onClick={()=>{setData(null);void load()}}>← ทุกร้าน</button><div><button className="btn secondary" onClick={()=>editRow('shop',data.shop!)}>แก้ไขชื่อร้าน</button><button className="btn danger-outline" onClick={()=>setDeleteShop(true)}><Trash2 size={16}/>ลบร้าน</button></div></div><nav className="admin-tabs">{[['activity','กิจกรรม'],['members','สมาชิก'],['products','สินค้า'],['sales','บิลขาย'],['entries','รายรับรายจ่าย'],['reports','รายงาน'],['audit','ประวัติ Admin']].map(([id,label])=><button className={`btn ${tab===id?'primary':'secondary'}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <section className="panel admin-list">
 {tab==='activity'&&activities.map(a=><article key={a.id}><div><strong>{a.title}</strong><p>{a.detail}</p><small>{thaiDate(a.time)}</small></div></article>)}
 {tab==='members'&&<AdminMembers data={data} onDone={async message=>{setNotice(message);await load(data.shop!.id)}}/>}
 {tab==='products'&&data.products.map(p=><article key={p.id}><div><strong>{p.name}</strong><p>{p.category} · {p.active?'เปิดขาย':'ปิดขาย'}</p><small>คงเหลือ {p.stock} · ราคา {baht(p.price)} · ต้นทุนเฉลี่ย {baht(p.average_cost)}</small></div><button className="btn secondary" onClick={()=>editRow('product',p)}>แก้ไข</button></article>)}
 {tab==='sales'&&data.sales.map(s=><article key={s.id}><div><strong>บิล #{s.bill_no} · {baht(s.total)} {s.voided_at?'· ยกเลิกแล้ว':''}</strong><p>{thaiDate(s.created_at)} · {s.payment==='cash'?'เงินสด':'เงินโอน'} · {s.customer_type==='Unspecified'?'ไม่ระบุประเภทลูกค้า':s.customer_type}</p>{data.items.filter(i=>i.sale_id===s.id).map(i=><small key={i.id}>{i.name} × {i.quantity} @ {baht(i.price)}<br/></small>)}{s.void_reason&&<p>{s.void_reason}</p>}{s.slip_path&&<details><summary>ดูสลิป</summary><Evidence path={s.slip_path}/></details>}</div>{!s.voided_at&&<div className="admin-tools"><button className="btn secondary" onClick={()=>editRow('sale',s)}>แก้ไขบิล</button><button className="btn secondary" onClick={()=>editRow('void_sale',s)}>ยกเลิกบิล</button></div>}</article>)}
 {tab==='entries'&&data.entries.map(e=><article key={e.id}><div><strong>{e.category} · {baht(e.amount)}</strong><p>{e.kind==='income'?'รายรับ':e.kind==='purchase'?'ซื้อสินค้า':'ค่าใช้จ่าย'} · {thaiDate(e.occurred_at)}</p><small>{e.note}</small>{e.evidence_path&&<details><summary>ดูหลักฐาน</summary><Evidence path={e.evidence_path}/></details>}</div><button className="btn secondary" onClick={()=>editRow('entry',e)}>แก้ไข</button></article>)}
 {tab==='audit'&&data.audit.map(a=><article key={a.id}><div><strong>{actionNames[a.action as keyof typeof actionNames]??a.action}</strong><p>{a.reason}</p><small>{thaiDate(a.created_at)} · ผู้แก้ไข {a.actor_id}</small><details><summary>ข้อมูลก่อน–หลัง</summary><pre>{JSON.stringify({ก่อน:a.before_data,หลัง:a.after_data},null,2)}</pre></details></div></article>)}
 {tab==='reports'&&<><div className="admin-tools"><label>จากวันที่<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>ถึงวันที่<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button className="btn soft" onClick={async()=>{try{const ex=await import('@/lib/exports');await ex.exportSalesTemplate(data,from,to)}catch(e){setError(errorText(e))}}}>Excel ส่งอาจารย์</button>{(['Excel','PDF'] as const).map(kind=><button className="btn secondary" key={kind} onClick={async()=>{try{const ex=await import('@/lib/exports');await (kind==='Excel'?ex.exportExcel:ex.exportPDF)(data,from,to)}catch(e){setError(errorText(e))}}}>{kind}</button>)}</div>{summaryRows(report(data,from,to)).map(([k,v])=><article key={String(k)}><span>{k}</span><b>{k.startsWith('จำนวน')?String(v):money(v)}</b></article>)}</>}
 </section></>}
 {edit&&data&&<Modal title={actionNames[edit.action]} onClose={()=>setEdit(null)}><AdminEdit edit={edit} data={data} onDone={async()=>{setEdit(null);setNotice('บันทึกแล้ว พร้อมเก็บประวัติการแก้ไข');await load(data.shop!.id)}}/></Modal>}
 {deleteShop&&data?.shop&&<Modal title="ยืนยันการลบร้าน" onClose={()=>setDeleteShop(false)}><DeleteShop shop={data.shop} onDone={async()=>{setDeleteShop(false);setData(null);setNotice('ลบร้านและข้อมูลที่เกี่ยวข้องเรียบร้อย');await load()}}/></Modal>}
 </main>;
}

function AdminMembers({data,onDone}:{data:ShopData;onDone:(message:string)=>Promise<void>}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const email=String(new FormData(form).get('email'));await rpc('makeit_admin_add_member',{p_shop:data.shop!.id,p_email:email});form.reset();await onDone('เพิ่มสมาชิกเข้าร้านแล้ว')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function remove(userId:string,email:string){if(!confirm(`ถอด ${email} ออกจากร้านนี้?`))return;setBusy(true);setError('');try{await rpc('makeit_admin_remove_member',{p_shop:data.shop!.id,p_user:userId});await onDone('ถอดสมาชิกออกจากร้านแล้ว')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <div className="admin-members"><div className="admin-members-head"><div><h2>สิทธิ์สมาชิกในร้าน</h2><p>เพิ่มบัญชีที่สมัครและยืนยันอีเมลแล้ว สมาชิกใช้งานหน้าร้านได้แต่ส่งออกไฟล์ไม่ได้</p></div><span className="count-badge">{Math.max(0,data.members.length-1)} สมาชิก</span></div><form className="admin-member-add" onSubmit={add}><label>อีเมลสมาชิก<input name="email" type="email" placeholder="member@example.com" required/></label><button className="btn primary" disabled={busy}><UserPlusIcon/>เพิ่มสิทธิ์</button></form><div className="member-list admin-member-list">{data.members.map(member=><div key={member.user_id}><span className="member-avatar">{member.email.slice(0,1).toUpperCase()}</span><div><strong>{member.email}</strong><small>{member.role==='owner'?'เจ้าของร้าน · สิทธิ์เต็ม':'สมาชิก · ไม่สามารถ Export'}</small></div><span className={`role-chip ${member.role}`}>{member.role==='owner'?'OWNER':'MEMBER'}</span>{member.role==='member'&&<button className="text-button danger" disabled={busy} onClick={()=>void remove(member.user_id,member.email)}>ถอดออก</button>}</div>)}</div>{error&&<div className="alert error">{error}</div>}</div>
}
function UserPlusIcon(){return <Users size={17}/>}
function DeleteShop({shop,onDone}:{shop:{id:string;name:string};onDone:()=>Promise<void>}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[typed,setTyped]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(typed!==shop.name){setError('กรุณาพิมพ์ชื่อร้านให้ตรงกัน');return}setBusy(true);setError('');try{const form=new FormData(e.currentTarget),{data:{session}}=await supabase().auth.getSession();if(!session)throw new Error('กรุณาเข้าสู่ระบบใหม่');const response=await fetch('/api/admin/delete-shop',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({shopId:shop.id,secret:form.get('secret')})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??'ลบร้านไม่สำเร็จ');await onDone()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <form className="delete-shop-form" onSubmit={submit}><div className="danger-zone"><Trash2 size={26}/><div><strong>การลบร้านไม่สามารถย้อนกลับได้</strong><p>สินค้า บิล สต็อก รายรับรายจ่าย สมาชิก และไฟล์หลักฐานของร้านจะถูกลบทั้งหมด</p></div></div><label>พิมพ์ชื่อร้าน “{shop.name}”<input value={typed} onChange={e=>setTyped(e.target.value)} required/></label><label>รหัสยืนยัน Admin<input name="secret" type="password" autoComplete="off" required/><small>ตั้งค่าผ่าน Secret ชื่อ ADMIN_ACTION_SECRET บน Vercel</small></label>{error&&<div className="alert error">{error}</div>}<button className="btn danger-button full" disabled={busy||typed!==shop.name}>{busy?'กำลังลบร้าน…':'ยืนยันลบร้านถาวร'}</button></form>
}

function AdminEdit({edit,data,onDone}:{edit:Edit;data:ShopData;onDone:()=>Promise<void>}){
 const{action,row}=edit;const[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[payment,setPayment]=useState(row.payment??'cash');
 const[items,setItems]=useState(data.items.filter(i=>i.sale_id===row.id).map(i=>({id:i.product_id,quantity:i.quantity,price:Number(i.price)})));
 const request=useRef(crypto.randomUUID()),lock=useRef(false),attempt=useRef<Record<string,unknown>|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  if(!attempt.current){const f=new FormData(e.currentTarget);let values:Record<string,unknown>={};
   if(action==='shop')values={name:f.get('name')};
   if(action==='product')values={name:f.get('name'),category:f.get('category'),price:f.get('price'),average_cost:f.get('average_cost'),stock:f.get('stock'),active:f.get('active')==='on'};
   if(action==='entry')values={kind:f.get('kind'),category:f.get('category'),amount:f.get('amount'),note:f.get('note'),occurred_at:new Date(`${f.get('occurred_at')}+07:00`).toISOString()};
   if(action==='sale'){const path=file?await upload(data.shop!.id,file):row.slip_path;if(payment==='transfer'&&!path)throw new Error('กรุณาแนบสลิปสำหรับเงินโอน');values={items,payment,slip_path:payment==='transfer'?path:null,created_at:new Date(`${f.get('created_at')}+07:00`).toISOString(),customer_type:f.get('customer_type'),time_source:row.time_source}}
   attempt.current={p_request:request.current,p_shop:data.shop!.id,p_action:action,p_target:row.id,p_expected:row,p_data:values,p_reason:f.get('reason')};
  }
  await rpc('makeit_admin_mutate',attempt.current);await onDone();
 }catch(e){setError(errorText(e))}finally{setBusy(false);lock.current=false}}
 const field=(name:string,label:string,type='text',value:unknown=row[name])=><label key={name}>{label}<input name={name} type={type} defaultValue={String(value??'')} required={!['note','category'].includes(name)} min={type==='number'?0:undefined} step={name==='stock'?'1':type==='number'?'0.000001':undefined}/></label>;
 return <form onSubmit={submit}><fieldset disabled={busy||!!attempt.current} className="admin-fieldset">
 {action==='shop'&&field('name','ชื่อร้าน')}
 {action==='product'&&<>{field('name','ชื่อสินค้า')}{field('category','หมวดหมู่')}{field('price','ราคาขาย','number')}{field('average_cost','ต้นทุนเฉลี่ยปัจจุบัน','number')}{field('stock','จำนวนคงเหลือ','number')}<label><input name="active" type="checkbox" defaultChecked={row.active}/> เปิดขาย</label><p>ปรับสต็อกและต้นทุนปัจจุบันโดยไม่เปลี่ยนต้นทุนในบิลเดิม และไม่สร้างเงินออก</p></>}
 {action==='entry'&&<><label>ประเภท<select name="kind" defaultValue={row.kind}>{row.kind==='purchase'?<option value="purchase">ซื้อสินค้า</option>:<><option value="income">รายรับ</option><option value="expense">ค่าใช้จ่าย</option></>}</select></label>{field('category','หมวดหมู่')}{field('amount','จำนวนเงิน','number')}{field('occurred_at','วันเวลา (ไทย)','datetime-local',localTime(row.occurred_at))}{field('note','หมายเหตุ')}{row.kind==='purchase'&&<p>แก้ยอดเงินที่จ่ายเท่านั้น ไม่เปลี่ยนต้นทุนสต็อกหรือบิลย้อนหลัง</p>}</>}
 {action==='void_sale'&&<p>ยกเลิกทั้งบิล #{row.bill_no} และคืนสต็อก โดยเก็บบิลและหลักฐานเดิมไว้</p>}
 {action==='sale'&&<><p>บิลเดิมจะถูกยกเลิกและสร้างบิลแก้ไข พร้อมปรับสต็อกในรายการเดียว</p>{field('created_at','เวลาขาย (ไทย)','datetime-local',localTime(row.created_at))}<label>ประเภทลูกค้า<select name="customer_type" defaultValue={row.customer_type??'Unspecified'}><option value="Student">Student — นักเรียน/นักศึกษา</option><option value="Office">Office — คนทำงาน</option><option value="Family">Family — ครอบครัว</option><option value="Other">Other — อื่น ๆ</option><option value="Unspecified">ไม่ระบุ (ข้อมูลเดิม)</option></select></label><label>วิธีชำระ<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">เงินสด</option><option value="transfer">เงินโอน</option></select></label>{payment==='transfer'&&<>{row.slip_path&&<Evidence path={row.slip_path}/>}<FileField label="สลิปใหม่ (หากต้องการเปลี่ยน)" onChange={setFile}/></>}{items.map((i,n)=><div className="admin-item" key={i.id}><strong>{data.products.find(p=>p.id===i.id)?.name}</strong><label>จำนวน<input type="number" min="1" step="1" required value={i.quantity} onChange={e=>setItems(items.map((v,j)=>j===n?{...v,quantity:Number(e.target.value)}:v))}/></label><label>ราคาต่อชิ้น<input type="number" min="0" step="0.01" required value={i.price} onChange={e=>setItems(items.map((v,j)=>j===n?{...v,price:Number(e.target.value)}:v))}/></label><button type="button" className="text-button" onClick={()=>setItems(items.filter((_,j)=>j!==n))}>นำออก</button></div>)}<label>เพิ่มสินค้า<select value="" onChange={e=>{const p=data.products.find(p=>p.id===e.target.value);if(p)setItems([...items,{id:p.id,quantity:1,price:Number(p.price)}])}}><option value="">เลือกสินค้า</option>{data.products.filter(p=>p.active&&!items.some(i=>i.id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}
 <label>เหตุผลการแก้ไข *<textarea name="reason" required maxLength={500} placeholder="อธิบายข้อมูลที่ผิดและเหตุผลในการแก้ไข"/></label></fieldset>
 {error&&<div className="alert error" role="alert">{error}{attempt.current&&<p>ลองส่งคำขอเดิมอีกครั้งได้ หากต้องการเปลี่ยนข้อมูลให้ปิดแล้วเปิดรายการใหม่</p>}</div>}<Submit busy={busy}>{attempt.current?'ลองส่งคำขอเดิมอีกครั้ง':'ยืนยันและเก็บประวัติ'}</Submit></form>;
}

