'use client';
import {useEffect,useRef,useState} from 'react';
import Auth from '@/components/auth';
import {Logo,Modal,Submit,Evidence,FileField,errorText} from '@/components/ui';
import {rpc,supabase,upload} from '@/lib/supabase';
import type {Snapshot} from '@/lib/types';
import {baht,money,thaiDate,thaiDay,summaryRows,report} from '@/lib/reports';

type Audit={id:string;actor_id:string;action:string;reason:string;created_at:string;before_data:unknown;after_data:unknown};
type ShopData=Snapshot & {owner_email:string;audit:Audit[]};
type Overview={total_shops:number;matched_shops:number;total_sales:number;total_revenue:number;total_corrections:number;shops:{id:string;name:string;email:string;product_count:number;sale_count:number;revenue:number;last_activity:string}[]};
type Edit={action:'shop'|'product'|'entry'|'sale'|'void_sale';row:Record<string,any>};
const movementNames:Record<string,string>={opening:'สต็อกเริ่มต้น',purchase:'รับสินค้าเข้า',adjustment:'ปรับสต็อก',sale:'ขายสินค้า',void:'คืนสต็อกจากยกเลิกบิล'};
const actionNames={shop:'ชื่อร้าน',product:'สินค้าและสต็อก',entry:'รายรับรายจ่าย',sale:'แก้ไขบิล',void_sale:'ยกเลิกบิล'};
const localTime=(s:string)=>new Date(new Date(s).getTime()+7*3600000).toISOString().slice(0,16);

export default function Admin(){
 const[uid,setUid]=useState<string|null>(null),[ready,setReady]=useState(false),[allowed,setAllowed]=useState<boolean|null>(null);
 const[overview,setOverview]=useState<Overview|null>(null),[data,setData]=useState<ShopData|null>(null),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[tab,setTab]=useState('activity');
 const[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[from,setFrom]=useState(thaiDay()),[to,setTo]=useState(thaiDay());
 const identity=useRef<string|null>(null);const generation=useRef(0);
 useEffect(()=>{const sb=supabase();const {data:{subscription}}=sb.auth.onAuthStateChange((_event,s)=>{const next=s?.user.id??null;if(identity.current!==next){identity.current=next;generation.current++;setAllowed(null);setData(null);setOverview(null);setEdit(null)}setUid(next);setReady(true)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!uid)return;let alive=true;rpc<boolean>('makeit_is_admin').then(v=>{if(alive)setAllowed(v)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[uid]);
 async function load(shopId?:string){const g=++generation.current;setLoading(true);setError('');try{if(shopId){const d=await rpc<ShopData>('makeit_admin_shop',{p_shop:shopId});if(g===generation.current)setData(d)}else{const d=await rpc<Overview>('makeit_admin_overview',{p_search:search,p_offset:offset});if(g===generation.current)setOverview(d)}}catch(e){if(g===generation.current)setError(errorText(e))}finally{if(g===generation.current)setLoading(false)}}
 useEffect(()=>{if(allowed)void load()},[allowed,offset]);
 if(!ready)return <main className="auth-page">กำลังโหลด…</main>;
 if(!uid)return <Auth onRecovered={()=>{}}/>;
 if(allowed!==true)return <main className="auth-page"><div className="auth-card"><Logo/><h1>{allowed===false?'ไม่มีสิทธิ์เข้าหน้า Admin':'กำลังตรวจสอบสิทธิ์…'}</h1>{error&&<p role="alert">{error}</p>}<a className="btn primary" href="/">กลับหน้าร้าน</a><button className="btn secondary" onClick={()=>supabase().auth.signOut()}>ออกจากระบบ</button></div></main>;
 const editRow=(action:Edit['action'],row:object)=>setEdit({action,row});
 const activities=data?[...data.movements.map(m=>({id:m.id,time:m.created_at,title:`${data.products.find(p=>p.id===m.product_id)?.name??'สินค้า'} · ${movementNames[m.kind]??m.kind}`,detail:`${m.quantity>0?'+':''}${m.quantity} ชิ้น · ${m.reason??''}`})),...data.entries.map(e=>({id:e.id,time:e.occurred_at,title:e.category,detail:`${baht(e.amount)} · ${e.note}`}))].sort((a,b)=>b.time.localeCompare(a.time)):[];
 return <main className="admin-page"><header className="admin-header"><Logo/><div><strong>MAKE IT Admin</strong><small>จัดการร้านค้าและตรวจสอบการแก้ไข</small></div><a className="btn secondary" href="/">หน้าร้าน</a><button className="btn secondary" onClick={()=>supabase().auth.signOut()}>ออกจากระบบ</button></header>
 {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert" role="status">{notice}</div>}
 <div className="page-heading"><div><span className="eyebrow">ADMIN WORKSPACE</span><h1>{data?.shop?.name??'ภาพรวมร้านค้า'}</h1><p>{data?data.owner_email:'ตรวจจำนวนร้าน กิจกรรม และช่วยแก้ไขข้อมูลที่บันทึกผิด'}</p></div><button className="btn secondary" disabled={loading} onClick={()=>load(data?.shop?.id)}>{loading?'กำลังโหลด…':'รีเฟรช'}</button></div>
 {!data&&overview&&<><div className="admin-stats">{[['ร้านค้าทั้งหมด',overview.total_shops],['บิลสำเร็จ',overview.total_sales],['ยอดขายรวม',baht(overview.total_revenue)],['การแก้ไขโดย Admin',overview.total_corrections]].map(([k,v])=><div className="panel" key={k}><small>{k}</small><h2>{v}</h2></div>)}</div><form className="admin-tools" onSubmit={e=>{e.preventDefault();if(offset)setOffset(0);else void load()}}><input aria-label="ค้นหาร้าน" placeholder="ค้นหาชื่อร้านหรืออีเมล" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn primary">ค้นหา</button></form><section className="panel">{overview.shops.map(s=><button className="sale-row" key={s.id} onClick={()=>{setTab('activity');void load(s.id)}}><div className="row-main"><strong>{s.name}</strong><small>{s.email}</small><small>{s.product_count} สินค้า · {s.sale_count} บิล · ล่าสุด {thaiDate(s.last_activity)}</small></div><b>{baht(s.revenue)}</b></button>)}{!overview.shops.length&&<p>ไม่พบร้านค้า</p>}</section><div className="admin-tools"><button className="btn secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>ก่อนหน้า</button><span>{offset+1}–{offset+overview.shops.length} จาก {overview.matched_shops}</span><button className="btn secondary" disabled={offset+30>=overview.matched_shops} onClick={()=>setOffset(offset+30)}>ถัดไป</button></div></>}
 {data&&data.shop&&<><div className="admin-tools"><button className="btn secondary" onClick={()=>{setData(null);void load()}}>← ทุกร้าน</button><button className="btn secondary" onClick={()=>editRow('shop',data.shop!)}>แก้ไขชื่อร้าน</button></div><nav className="admin-tabs">{[['activity','กิจกรรม'],['products','สินค้า'],['sales','บิลขาย'],['entries','รายรับรายจ่าย'],['reports','รายงาน'],['audit','ประวัติ Admin']].map(([id,label])=><button className={`btn ${tab===id?'primary':'secondary'}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <section className="panel admin-list">
 {tab==='activity'&&activities.map(a=><article key={a.id}><div><strong>{a.title}</strong><p>{a.detail}</p><small>{thaiDate(a.time)}</small></div></article>)}
 {tab==='products'&&data.products.map(p=><article key={p.id}><div><strong>{p.name}</strong><p>{p.category} · {p.active?'เปิดขาย':'ปิดขาย'}</p><small>คงเหลือ {p.stock} · ราคา {baht(p.price)} · ต้นทุนเฉลี่ย {baht(p.average_cost)}</small></div><button className="btn secondary" onClick={()=>editRow('product',p)}>แก้ไข</button></article>)}
 {tab==='sales'&&data.sales.map(s=><article key={s.id}><div><strong>บิล #{s.bill_no} · {baht(s.total)} {s.voided_at?'· ยกเลิกแล้ว':''}</strong><p>{thaiDate(s.created_at)} · {s.payment==='cash'?'เงินสด':'เงินโอน'} · {s.customer_type==='Unspecified'?'ไม่ระบุประเภทลูกค้า':s.customer_type}</p>{data.items.filter(i=>i.sale_id===s.id).map(i=><small key={i.id}>{i.name} × {i.quantity} @ {baht(i.price)}<br/></small>)}{s.void_reason&&<p>{s.void_reason}</p>}{s.slip_path&&<details><summary>ดูสลิป</summary><Evidence path={s.slip_path}/></details>}</div>{!s.voided_at&&<div className="admin-tools"><button className="btn secondary" onClick={()=>editRow('sale',s)}>แก้ไขบิล</button><button className="btn secondary" onClick={()=>editRow('void_sale',s)}>ยกเลิกบิล</button></div>}</article>)}
 {tab==='entries'&&data.entries.map(e=><article key={e.id}><div><strong>{e.category} · {baht(e.amount)}</strong><p>{e.kind==='income'?'รายรับ':e.kind==='purchase'?'ซื้อสินค้า':'ค่าใช้จ่าย'} · {thaiDate(e.occurred_at)}</p><small>{e.note}</small>{e.evidence_path&&<details><summary>ดูหลักฐาน</summary><Evidence path={e.evidence_path}/></details>}</div><button className="btn secondary" onClick={()=>editRow('entry',e)}>แก้ไข</button></article>)}
 {tab==='audit'&&data.audit.map(a=><article key={a.id}><div><strong>{actionNames[a.action as keyof typeof actionNames]??a.action}</strong><p>{a.reason}</p><small>{thaiDate(a.created_at)} · ผู้แก้ไข {a.actor_id}</small><details><summary>ข้อมูลก่อน–หลัง</summary><pre>{JSON.stringify({ก่อน:a.before_data,หลัง:a.after_data},null,2)}</pre></details></div></article>)}
 {tab==='reports'&&<><div className="admin-tools"><label>จากวันที่<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>ถึงวันที่<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button className="btn soft" onClick={async()=>{try{const ex=await import('@/lib/exports');await ex.exportSalesTemplate(data,from,to)}catch(e){setError(errorText(e))}}}>Excel ส่งอาจารย์</button>{(['Excel','PDF'] as const).map(kind=><button className="btn secondary" key={kind} onClick={async()=>{try{const ex=await import('@/lib/exports');await (kind==='Excel'?ex.exportExcel:ex.exportPDF)(data,from,to)}catch(e){setError(errorText(e))}}}>{kind}</button>)}</div>{summaryRows(report(data,from,to)).map(([k,v])=><article key={String(k)}><span>{k}</span><b>{k.startsWith('จำนวน')?String(v):money(v)}</b></article>)}</>}
 </section></>}
 {edit&&data&&<Modal title={actionNames[edit.action]} onClose={()=>setEdit(null)}><AdminEdit edit={edit} data={data} onDone={async()=>{setEdit(null);setNotice('บันทึกแล้ว พร้อมเก็บประวัติการแก้ไข');await load(data.shop!.id)}}/></Modal>}
 </main>;
}

function AdminEdit({edit,data,onDone}:{edit:Edit;data:ShopData;onDone:()=>Promise<void>}){
 const{action,row}=edit;const[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[payment,setPayment]=useState(row.payment??'cash');
 const[items,setItems]=useState(data.items.filter(i=>i.sale_id===row.id).map(i=>({id:i.product_id,quantity:i.quantity,price:Number(i.price)})));
 const request=useRef(crypto.randomUUID()),lock=useRef(false),attempt=useRef<Record<string,unknown>|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  if(!attempt.current){const f=new FormData(e.currentTarget);let values:Record<string,unknown>={};
   if(action==='shop')values={name:f.get('name')};
   if(action==='product')values={name:f.get('name'),category:f.get('category'),price:f.get('price'),average_cost:f.get('average_cost'),stock:f.get('stock'),active:f.get('active')==='on'};
   if(action==='entry')values={kind:f.get('kind'),category:f.get('category'),amount:f.get('amount'),note:f.get('note'),occurred_at:new Date(`${f.get('occurred_at')}+07:00`).toISOString()};
   if(action==='sale'){const path=file?await upload(data.shop!.id,file):row.slip_path;if(payment==='transfer'&&!path)throw new Error('กรุณาแนบสลิปสำหรับเงินโอน');values={items,payment,slip_path:payment==='transfer'?path:null,created_at:new Date(`${f.get('created_at')}+07:00`).toISOString(),customer_type:f.get('customer_type'),time_source:row.time_source}}
   attempt.current={p_request:request.current,p_shop:data.shop!.id,p_action:action,p_target:row.id,p_expected:row,p_data:values,p_reason:f.get('reason')};
  }
  await rpc('makeit_admin_mutate',attempt.current);await onDone();
 }catch(e){setError(errorText(e))}finally{setBusy(false);lock.current=false}}
 const field=(name:string,label:string,type='text',value:unknown=row[name])=><label key={name}>{label}<input name={name} type={type} defaultValue={String(value??'')} required={!['note','category'].includes(name)} min={type==='number'?0:undefined} step={name==='stock'?'1':type==='number'?'0.000001':undefined}/></label>;
 return <form onSubmit={submit}><fieldset disabled={busy||!!attempt.current} className="admin-fieldset">
 {action==='shop'&&field('name','ชื่อร้าน')}
 {action==='product'&&<>{field('name','ชื่อสินค้า')}{field('category','หมวดหมู่')}{field('price','ราคาขาย','number')}{field('average_cost','ต้นทุนเฉลี่ยปัจจุบัน','number')}{field('stock','จำนวนคงเหลือ','number')}<label><input name="active" type="checkbox" defaultChecked={row.active}/> เปิดขาย</label><p>ปรับสต็อกและต้นทุนปัจจุบันโดยไม่เปลี่ยนต้นทุนในบิลเดิม และไม่สร้างเงินออก</p></>}
 {action==='entry'&&<><label>ประเภท<select name="kind" defaultValue={row.kind}>{row.kind==='purchase'?<option value="purchase">ซื้อสินค้า</option>:<><option value="income">รายรับ</option><option value="expense">ค่าใช้จ่าย</option></>}</select></label>{field('category','หมวดหมู่')}{field('amount','จำนวนเงิน','number')}{field('occurred_at','วันเวลา (ไทย)','datetime-local',localTime(row.occurred_at))}{field('note','หมายเหตุ')}{row.kind==='purchase'&&<p>แก้ยอดเงินที่จ่ายเท่านั้น ไม่เปลี่ยนต้นทุนสต็อกหรือบิลย้อนหลัง</p>}</>}
 {action==='void_sale'&&<p>ยกเลิกทั้งบิล #{row.bill_no} และคืนสต็อก โดยเก็บบิลและหลักฐานเดิมไว้</p>}
 {action==='sale'&&<><p>บิลเดิมจะถูกยกเลิกและสร้างบิลแก้ไข พร้อมปรับสต็อกในรายการเดียว</p>{field('created_at','เวลาขาย (ไทย)','datetime-local',localTime(row.created_at))}<label>ประเภทลูกค้า<select name="customer_type" defaultValue={row.customer_type??'Unspecified'}><option value="Student">Student — นักเรียน/นักศึกษา</option><option value="Office">Office — คนทำงาน</option><option value="Family">Family — ครอบครัว</option><option value="Unspecified">ไม่ระบุ (ข้อมูลเดิม)</option></select></label><label>วิธีชำระ<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">เงินสด</option><option value="transfer">เงินโอน</option></select></label>{payment==='transfer'&&<>{row.slip_path&&<Evidence path={row.slip_path}/>}<FileField label="สลิปใหม่ (หากต้องการเปลี่ยน)" onChange={setFile}/></>}{items.map((i,n)=><div className="admin-item" key={i.id}><strong>{data.products.find(p=>p.id===i.id)?.name}</strong><label>จำนวน<input type="number" min="1" step="1" required value={i.quantity} onChange={e=>setItems(items.map((v,j)=>j===n?{...v,quantity:Number(e.target.value)}:v))}/></label><label>ราคาต่อชิ้น<input type="number" min="0" step="0.01" required value={i.price} onChange={e=>setItems(items.map((v,j)=>j===n?{...v,price:Number(e.target.value)}:v))}/></label><button type="button" className="text-button" onClick={()=>setItems(items.filter((_,j)=>j!==n))}>นำออก</button></div>)}<label>เพิ่มสินค้า<select value="" onChange={e=>{const p=data.products.find(p=>p.id===e.target.value);if(p)setItems([...items,{id:p.id,quantity:1,price:Number(p.price)}])}}><option value="">เลือกสินค้า</option>{data.products.filter(p=>p.active&&!items.some(i=>i.id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}
 <label>เหตุผลการแก้ไข *<textarea name="reason" required maxLength={500} placeholder="อธิบายข้อมูลที่ผิดและเหตุผลในการแก้ไข"/></label></fieldset>
 {error&&<div className="alert error" role="alert">{error}{attempt.current&&<p>ลองส่งคำขอเดิมอีกครั้งได้ หากต้องการเปลี่ยนข้อมูลให้ปิดแล้วเปิดรายการใหม่</p>}</div>}<Submit busy={busy}>{attempt.current?'ลองส่งคำขอเดิมอีกครั้ง':'ยืนยันและเก็บประวัติ'}</Submit></form>;
}

