'use client';
import {useState} from 'react';
import {ArrowRight,ShieldCheck,Smartphone,ChartNoAxesCombined,Check} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Logo,Submit,errorText} from './ui';
export default function Auth({recovery=false,onRecovered}:{recovery?:boolean;onRecovered:()=>void}){
 const[mode,setMode]=useState<'login'|'signup'|'reset'>('login');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));
 try{
  if(recovery){const{error}=await supabase().auth.updateUser({password});if(error)throw error;onRecovered();return;}
  if(mode==='login'){const{error}=await supabase().auth.signInWithPassword({email,password});if(error)throw error;}
  if(mode==='signup'){const{error}=await supabase().auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(error)throw error;setMessage('สมัครสำเร็จ กรุณาตรวจอีเมลเพื่อยืนยันบัญชี แล้วกลับมาเข้าสู่ระบบ');}
  if(mode==='reset'){const{error}=await supabase().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/?recovery=1`});if(error)throw error;setMessage('ส่งลิงก์ตั้งรหัสผ่านแล้ว กรุณาตรวจอีเมลและโฟลเดอร์สแปม');}
 }catch(err){const msg=errorText(err);setError(msg==='Invalid login credentials'?'อีเมลหรือรหัสผ่านไม่ถูกต้อง':msg==='Email not confirmed'?'กรุณายืนยันอีเมลก่อนเข้าสู่ระบบ':msg)}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-story"><Logo/><div className="story-main"><span className="eyebrow light">YOUR STORE. SIMPLIFIED.</span><h1>ทุกการขาย<br/>จัดการได้<br/><em>ในมือคุณ.</em></h1><p>ดูแลหน้าร้าน สต็อก และรายรับรายจ่าย<br/>ให้ทุกวันของการขาย เป็นเรื่องง่าย</p><div className="story-features"><span><Smartphone size={18}/>ขายสะดวกบนมือถือ</span><span><ChartNoAxesCombined size={18}/>เห็นภาพรวมร้านชัดเจน</span></div></div><div className="story-footer"><ShieldCheck size={16}/>ข้อมูลร้านปกป้องด้วยสิทธิ์การเข้าถึง</div><div className="decor-circle"/></section><section className="auth-form-side"><div className="auth-mobile-logo"><Logo/></div><div className="auth-form-wrap"><span className="eyebrow">MAKE EVERY SALE COUNT</span><h2>{recovery?'ตั้งรหัสผ่านใหม่':mode==='signup'?'เริ่มต้นร้านของคุณ':mode==='reset'?'ลืมรหัสผ่าน?':'ยินดีต้อนรับกลับมา'}</h2><p className="muted">{recovery?'ตั้งรหัสผ่านอย่างน้อย 8 ตัวอักษร':mode==='signup'?'สร้างบัญชีเพื่อเริ่มบันทึกการขายกับ MAKE IT':mode==='reset'?'เราจะส่งลิงก์ตั้งรหัสผ่านใหม่ไปทางอีเมล':'เข้าสู่ระบบ แล้วเริ่มวันดี ๆ ของร้านคุณ'}</p>{!recovery&&mode!=='reset'&&<div className="segmented"><button className={mode==='login'?'selected':''} onClick={()=>{setMode('login');setMessage('');setError('')}}>เข้าสู่ระบบ</button><button className={mode==='signup'?'selected':''} onClick={()=>{setMode('signup');setMessage('');setError('')}}>สมัครสมาชิก</button></div>}<form onSubmit={submit}>{!recovery&&<label>อีเมล<input name="email" type="email" placeholder="you@example.com" autoComplete="email" required/></label>}{(recovery||mode!=='reset')&&<label>รหัสผ่าน<input name="password" type="password" placeholder="อย่างน้อย 8 ตัวอักษร" minLength={8} autoComplete={mode==='login'&&!recovery?'current-password':'new-password'} required/></label>}{!recovery&&mode==='login'&&<button className="text-button forgot" type="button" onClick={()=>setMode('reset')}>ลืมรหัสผ่าน?</button>}{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success" role="status"><Check size={18}/>{message}</div>}<Submit busy={busy}>{recovery?'บันทึกรหัสผ่าน':mode==='signup'?'สร้างบัญชี':mode==='reset'?'ส่งลิงก์ตั้งรหัสผ่าน':'เข้าสู่ระบบ'}<ArrowRight size={18}/></Submit></form>{mode==='reset'&&<button className="text-button" onClick={()=>setMode('login')}>กลับไปเข้าสู่ระบบ</button>}<p className="auth-note"><ShieldCheck size={15}/>หนึ่งบัญชี หนึ่งร้าน ใช้ได้ทุกอุปกรณ์</p></div><footer>MAKE IT <span>Mobile POS System</span></footer></section></main>;
}
