'use client';
import {useRef,useState} from 'react';
import type {Product,Snapshot} from '@/lib/types';
import {rpc,upload} from '@/lib/supabase';
import {FileField,Submit,errorText,Photo} from './ui';
import {baht,thaiDay} from '@/lib/reports';
type Done={shopId:string;onDone:()=>Promise<void>};
export function ProductForm({product,shopId,onDone}:{product?:Product}&Done){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null);const id=useRef(product?.id??crypto.randomUUID());
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{
  const path=file?await upload(shopId,file):product?.image_path??null;
  await rpc('makeit_save_product',{p_id:id.current,p_name:f.get('name'),p_category:f.get('category'),p_price:Number(f.get('price')),p_cost:Number(f.get('cost')??0),p_stock:Number(f.get('stock')??0),p_active:f.get('active')==='on',p_image:path});await onDone();
 }catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <form onSubmit={submit}><label>ชื่อสินค้า<input name="name" defaultValue={product?.name} maxLength={160} required placeholder="เช่น กาแฟลาเต้"/></label><label>หมวดหมู่<input name="category" defaultValue={product?.category} maxLength={100} placeholder="เช่น เครื่องดื่ม"/></label><div className="form-grid"><label>ราคาขาย (บาท)<input name="price" type="number" min="0" max="999999999" step="0.01" defaultValue={product?.price} required inputMode="decimal"/></label>{!product&&<label>ต้นทุนต่อชิ้น (บาท)<input name="cost" type="number" min="0" max="999999999" step="0.01" required inputMode="decimal"/></label>}</div>{!product?<label>จำนวนเริ่มต้น (ชิ้น)<input name="stock" type="number" min="0" max="10000000" step="1" defaultValue={0} required inputMode="numeric"/><small>ยอดยกมา ไม่บันทึกเป็นเงินออกย้อนหลัง</small></label>:<div className="info-box">คงเหลือ {product.stock} ชิ้น • ต้นทุนเฉลี่ย {baht(product.average_cost)}<br/><small>เปลี่ยนจำนวนหรือต้นทุนผ่านเมนูจัดการสต็อก</small></div>}<FileField label="รูปสินค้า" onChange={setFile}/><label className="checkbox"><input name="active" type="checkbox" defaultChecked={product?.active??true}/>เปิดขายสินค้านี้</label>{error&&<div className="alert error" role="alert">{error}</div>}<Submit busy={busy}>บันทึกสินค้า</Submit></form>
}
export function StockForm({product,onDone}:{product:Product}&Done){
 const[kind,setKind]=useState('purchase'),[busy,setBusy]=useState(false),[error,setError]=useState('');const id=useRef(crypto.randomUUID());
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await rpc('makeit_stock',{p_request:id.current,p_product:product.id,p_kind:kind,p_quantity:Number(f.get('quantity')),p_cost:Number(f.get('cost')??0),p_paid:f.get('paid')==='on',p_reason:String(f.get('reason'))});await onDone()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <form onSubmit={submit}><div className="info-box"><strong>{product.name}</strong><p>คงเหลือ {product.stock} ชิ้น · ต้นทุนเฉลี่ย {baht(product.average_cost)}</p></div><div className="segmented"><button type="button" className={kind==='purchase'?'selected':''} onClick={()=>setKind('purchase')}>รับสินค้าเข้า</button><button type="button" className={kind==='adjustment'?'selected':''} onClick={()=>setKind('adjustment')}>ปรับยอดคงเหลือ</button></div><label>{kind==='purchase'?'จำนวนที่รับเข้า':'จำนวนคงเหลือที่ตรวจนับได้'}<input name="quantity" type="number" min={kind==='purchase'?1:0} max="10000000" step="1" required inputMode="numeric"/></label>{kind==='purchase'&&<><label>ต้นทุนซื้อครั้งนี้ต่อชิ้น (บาท)<input name="cost" type="number" min="0" max="999999999" step="0.01" required inputMode="decimal"/></label><label className="checkbox"><input name="paid" type="checkbox" defaultChecked/>จ่ายค่าสินค้าแล้ว — บันทึกเงินออกอัตโนมัติ</label><small>ถ้ายังไม่จ่าย เมื่อจ่ายจริงให้บันทึกค่าซื้อสินค้าจากรายการรับเข้านี้</small></>}<label>เหตุผล / หมายเหตุ<input name="reason" maxLength={500} required={kind==='adjustment'} placeholder={kind==='purchase'?'เช่น รับสินค้ารอบเช้า':'เช่น ตรวจนับสินค้าเสียหาย'}/></label>{error&&<div className="alert error">{error}</div>}<Submit busy={busy}>บันทึกสต็อก</Submit></form>
}
export function CashForm({shopId,onDone}:Done){
 const[kind,setKind]=useState('expense'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null);const id=useRef(crypto.randomUUID());
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const evidence=file?await upload(shopId,file):null;await rpc('makeit_cash',{p_id:id.current,p_kind:kind,p_category:f.get('category'),p_amount:Number(f.get('amount')),p_note:f.get('note'),p_occurred:new Date(`${f.get('date')}T${f.get('time')}:00+07:00`).toISOString(),p_evidence:evidence});await onDone()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <form onSubmit={submit}><div className="segmented"><button type="button" onClick={()=>setKind('expense')} className={kind==='expense'?'selected':''}>รายจ่าย</button><button type="button" onClick={()=>setKind('income')} className={kind==='income'?'selected':''}>รายรับอื่น</button></div><label>หมวดหมู่<input name="category" list="cash-categories" maxLength={100} placeholder={kind==='expense'?'เช่น ค่าเช่าร้าน':'เช่น รายได้บริการ'} required/><datalist id="cash-categories">{(kind==='expense'?['ค่าเช่าร้าน','ค่าน้ำค่าไฟ','ค่าขนส่ง','ค่าแรง','ค่าใช้จ่ายอื่น']:['รายได้บริการ','รายรับอื่น']).map(c=><option key={c} value={c}/>)}</datalist></label><label>จำนวนเงิน (บาท)<input name="amount" type="number" min="0.01" max="999999999" step="0.01" inputMode="decimal" required/></label><div className="form-grid"><label>วันที่<input name="date" type="date" defaultValue={thaiDay()} required/></label><label>เวลา<input name="time" type="time" defaultValue={new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'}).format(new Date())} required/></label></div><label>หมายเหตุ<textarea name="note" maxLength={1000} rows={2}/></label><FileField label="หลักฐาน (ถ้ามี)" onChange={setFile}/><div className="info-box">ค่าซื้อสินค้าให้บันทึกผ่านการรับสต็อก เพื่อไม่ให้หักต้นทุนซ้ำ</div>{error&&<div className="alert error">{error}</div>}<Submit busy={busy}>บันทึกรายการ</Submit></form>
}
